### ISSUE TITLE
Need help to run this project

### ISSUE THREAD

**Issue by umeshaik** [paulc4/microservices-demo#4]
In Readme, they mentioned to kill first account server and run the second one, how to kill the first instance server.?
Can we run more than one instance of a same service.If so,how to do it?Will the eureka dashboard displays how many instances of same service are running. 
Do we need to change any port settings in the code?I have no idea how to do that. Please explain the whole project how it is running clearly.
Please reply me as soon as possible.
Appreciate your help.

**Comment by geekosphere-net** [comment]
To kill the first one just `ctrl-c` your java process, or stop it in the IDE.
As for running more then one instance I had to add the following to the `accounts-service.yml` file

```
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
```

then each service registered with a unique `instanceId` into Eureka.
